// ─────────────────────────────────────────────────────────────
// api/report.js
// ACTION: REFACTORED from api/deploy-bot.js
//
//   POST /api/report     → generate Groq audit readiness report
//   GET  /api/report     → list saved reports for user
//   GET  /api/report?id= → get single report by ID
//
// KEPT:    Groq API call pattern (verbatim from analyze.js), Redis client,
//          auth middleware, CORS headers, error handling
// REMOVED: GitHub repo creation, file uploads to GitHub, Pages enabling,
//          agent tier HTML generation, deploy tracking
// ADDED:   SOC 2 audit report prompt (Section I), report save to Redis,
//          report retrieval by ID, structured JSON output,
//          disclaimer + evidenceSuggestions fields, company context,
//          aiGenerated transparency fields
// ─────────────────────────────────────────────────────────────

import { Redis } from '@upstash/redis';
import { trackUser, checkRateLimit, logError, verifySession, getUserMode, isPaidMode } from './_telemetry.js';

const redis = new Redis({
  url: process.env.KV_REST_API_URL,
  token: process.env.KV_REST_API_TOKEN,
});

// ── Auth helpers ─────────────────────────────────────────────

async function getUserId(authHeader) {
  if (!authHeader?.startsWith('Bearer ')) return null;
  const token = authHeader.slice(7);
  if (token.startsWith('s1.')) return verifySession(token);
  if (token.startsWith('google:') || token.startsWith('slack:')) return null;
  try {
    const r = await fetch('https://api.github.com/user', {
      headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json', 'User-Agent': 'AuditReady-AI' },
    });
    if (!r.ok) return null;
    const u = await r.json();
    return 'github:' + u.login;
  } catch { return null; }
}

// ── Groq API call (verbatim pattern from analyze.js) ─────────

function safeJsonParse(text) {
  try {
    let c = text.replace(/```json/g, '').replace(/```/g, '').trim();
    const s = c.indexOf('{'), e = c.lastIndexOf('}');
    if (s >= 0 && e > s) c = c.slice(s, e + 1);
    return JSON.parse(c);
  } catch { return null; }
}

async function groqPost(messages, maxTokens, temperature) {
  const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': 'Bearer ' + process.env.GROQ_API_KEY,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages,
      max_tokens: maxTokens || 1500,
      temperature: temperature ?? 0.15,
    }),
  });
  if (!res.ok) throw new Error('Groq error ' + res.status);
  const data = await res.json();
  return data.choices?.[0]?.message?.content || '';
}

// ── Report schema ─────────────────────────────────────────────

const REPORT_SCHEMA = {
  disclaimer: 'string — exactly: "This report was generated by AuditReady AI to help you prepare for a SOC 2 audit. It is not a certified audit opinion and does not replace an attestation by a licensed CPA firm."',
  executiveSummary: 'string — 2-3 sentences, business-focused, honest about gaps',
  readinessByCategory: {
    CC1: 'string — one paragraph, specific to this company\'s controls',
    CC2: 'string — one paragraph, specific to this company\'s controls',
    CC3: 'string — one paragraph, specific to this company\'s controls',
    CC4: 'string — one paragraph, specific to this company\'s controls',
    CC5: 'string — one paragraph, specific to this company\'s controls',
    CC6: 'string — one paragraph, specific to this company\'s controls',
    CC7: 'string — one paragraph, specific to this company\'s controls',
    CC8: 'string — one paragraph, specific to this company\'s controls',
    CC9: 'string — one paragraph, specific to this company\'s controls',
  },
  criticalGaps: [
    { controlId: 'string', title: 'string', remediationAction: 'string — concrete, specific action not generic advice', urgency: 'HIGH|MEDIUM|LOW' }
  ],
  evidenceSuggestions: {
    'CC-ID': 'string — specific document or evidence this company should create/gather for this exact control'
  },
  nextSteps: {
    thirtyDays: ['string — specific, actionable item'],
    sixtyDays: ['string — specific, actionable item'],
    ninetyDays: ['string — specific, actionable item'],
  },
  estimatedTimeToAuditReady: 'string — honest estimate based on number of NOT_STARTED controls, e.g. "4-6 months with focused effort"',
  overallRating: 'NOT_READY | IN_PROGRESS | GETTING_CLOSE | AUDIT_READY',
};

// ── Build controls summary for prompt ────────────────────────

async function buildControlsSummary(userId) {
  const ALL_CONTROLS = [
    'CC1.1','CC1.2','CC1.3','CC1.4',
    'CC2.1','CC2.2','CC2.3',
    'CC3.1','CC3.2','CC3.3',
    'CC4.1','CC4.2',
    'CC5.1','CC5.2','CC5.3','CC5.4','CC5.5',
    'CC6.1','CC6.2','CC6.3','CC6.4','CC6.5','CC6.6','CC6.7','CC6.8','CC6.9',
    'CC7.1','CC7.2','CC7.3','CC7.4','CC7.5','CC7.6',
    'CC8.1','CC8.2','CC8.3','CC8.4','CC8.5','CC8.6',
    'CC9.1','CC9.2','CC9.3','CC9.4','CC9.5','CC9.6','CC9.7','CC9.8','CC9.9','CC9.10','CC9.11',
  ];

  const summary = [];
  for (const id of ALL_CONTROLS) {
    const raw = await redis.get(`control:${userId}:${id}`);
    if (raw) {
      const c = typeof raw === 'object' ? raw : JSON.parse(raw);
      summary.push({ id: c.id || id, title: c.title, status: c.status, category: c.category || id.split('.')[0] });
    } else {
      summary.push({ id, status: 'NOT_STARTED', category: id.split('.')[0] });
    }
  }
  return summary;
}

// ── Get current score ─────────────────────────────────────────

async function getCurrentScore(userId) {
  try {
    const raw = await redis.get(`user:${userId}:score`);
    if (!raw) return 0;
    const data = typeof raw === 'object' ? raw : JSON.parse(raw);
    return data.score || 0;
  } catch { return 0; }
}

// ── Main handler ─────────────────────────────────────────────

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const userId = await getUserId(req.headers.authorization);
  if (!userId) return res.status(401).json({ error: 'Unauthorized' });

  // ── GET: List reports or get single report ────────────────────
  if (req.method === 'GET') {
    // ── GET ?type=policy&controlId=X — generate policy doc via Groq ──
    if (req.query.type === 'policy') {
      const { controlId } = req.query;
      if (!controlId) return res.status(400).json({ error: 'Missing controlId' });
      if (!process.env.GROQ_API_KEY) return res.status(500).json({ error: 'GROQ_API_KEY not configured' });
      // AI policy generation is a paid feature — enforce server-side, not just
      // in the UI, so a free user can't call this endpoint directly.
      if (!isPaidMode(await getUserMode(userId))) {
        return res.status(402).json({ error: 'AI policy generation requires a paid plan.' });
      }
      const cacheKey = `policy:${controlId}`;
      const cached = await redis.get(cacheKey);
      if (cached) return res.status(200).json(typeof cached === 'object' ? cached : JSON.parse(cached));
      const POLICY_PROMPTS = {
        'CC1.1': { name: 'Information Security Policy', guidance: 'Write a complete Information Security Policy for a SaaS startup. Include: purpose, scope, roles & responsibilities (CISO/CTO ownership), asset management, acceptable use, password requirements, incident reporting obligation, annual review requirement. Use professional legal language. Aim for 600-900 words.' },
        'CC1.3': { name: 'Code of Conduct & Ethics Policy', guidance: 'Write a Code of Conduct and Ethics Policy for a SaaS company. Include: purpose, scope (all employees/contractors), expected behaviors, conflicts of interest, confidentiality, data handling ethics, reporting violations, consequences. 400-600 words.' },
        'CC2.1': { name: 'Security Awareness Training Policy', guidance: 'Write a Security Awareness Training Policy. Include: purpose, mandatory training schedule (new hire + annual), topics covered (phishing, data handling, password hygiene, incident reporting), completion tracking, consequences for non-completion. 300-500 words.' },
        'CC2.2': { name: 'Incident Communication Procedure', guidance: 'Write an Incident Communication Procedure. Include: purpose, incident severity levels (P1-P4), notification timelines per severity, customer notification within 72hrs for data breach, communication templates, post-incident report requirement. 500-700 words.' },
        'CC3.1': { name: 'Risk Assessment Procedure', guidance: 'Write a Risk Assessment Procedure for a SaaS company. Include: purpose, scope, methodology (likelihood 1-5 × impact 1-5), risk categories, risk owner assignment, review frequency (annual + on major changes), risk treatment options. 500-700 words.' },
        'CC5.3': { name: 'Data Retention & Disposal Policy', guidance: 'Write a Data Retention and Disposal Policy. Include: purpose, data categories and retention periods, secure disposal methods, disposal verification, customer data deletion on contract termination. 400-600 words.' },
        'CC5.4': { name: 'Encryption Key Management Procedure', guidance: 'Write an Encryption Key Management Procedure. Include: purpose, key types in use (TLS, data-at-rest, API keys), key generation, storage (HSM or KMS), rotation schedule (annual, immediate on compromise), retirement and destruction. 400-600 words.' },
        'CC5.5': { name: 'Data Classification Policy', guidance: 'Write a Data Classification Policy. Include: purpose, four classification levels (Public, Internal, Confidential, Restricted), definitions and examples, handling requirements per level, labeling requirements, employee responsibilities. 400-600 words.' },
        'CC6.3': { name: 'Unique User Account Policy', guidance: 'Write a Unique User Account and Credential Management Policy. Include: purpose, prohibition of shared credentials, unique account requirement for all systems, naming convention, account provisioning, service account management, periodic review. 300-500 words.' },
        'CC6.4': { name: 'Access Review Procedure', guidance: 'Write a Quarterly Access Review Procedure. Include: purpose, scope (all production systems and SaaS tools), review frequency, reviewer responsibilities, review steps, actions for inappropriate access, documentation requirements. 400-500 words.' },
        'CC6.5': { name: 'Employee Offboarding Security Procedure', guidance: 'Write an Employee Offboarding Security Procedure. Include: purpose, trigger (termination, resignation, role change), 24-hour access revocation SLA, system checklist, responsible parties, verification step, documentation requirement. 400-600 words.' },
        'CC6.7': { name: 'Password Policy', guidance: 'Write a Password Policy. Include: purpose, minimum requirements (16+ chars, complexity, no reuse of last 12), prohibition of sharing, MFA requirement, approved password manager, admin account requirements, breach response. 300-500 words.' },
        'CC6.9': { name: 'Remote Access Security Policy', guidance: 'Write a Remote Access Security Policy. Include: purpose, approved access methods (VPN, zero-trust), MFA requirement, device requirements, prohibited activities (public WiFi without VPN), session timeout, logging. 300-500 words.' },
        'CC7.3': { name: 'Incident Response Plan', guidance: 'Write a complete Incident Response Plan (IRP). Include: purpose, scope, severity definitions (P1-P4 with examples), response team roles (Incident Commander, Tech Lead, Communications Lead), step-by-step procedures (Detect → Contain → Eradicate → Recover → Review), communication matrix, post-incident review, 30-day remediation tracking. 800-1200 words.' },
        'CC7.6': { name: 'System Performance & Capacity Management Policy', guidance: 'Write a System Performance and Capacity Management Policy. Include: purpose, monitoring requirements (CPU <80%, memory <85%, disk <80%), alerting SLAs, capacity planning review (quarterly), scaling procedures, performance baseline documentation. 300-400 words.' },
        'CC8.6': { name: 'Rollback Procedure', guidance: 'Write a Deployment Rollback Procedure. Include: purpose, rollback triggers (error rate threshold, latency spike, failed health checks), decision authority, rollback steps, time objective (RTO: 15 minutes), post-rollback actions (incident report, root cause analysis). 400-600 words.' },
        'CC9.1': { name: 'Vendor Risk Assessment Procedure', guidance: 'Write a Vendor Risk Assessment Procedure. Include: purpose, vendor tiers (Critical/Important/Standard), assessment requirements per tier, frequency (annual for Critical/Important), risk scoring, escalation for high-risk vendors. 500-700 words.' },
        'CC9.3': { name: 'Business Continuity Plan', guidance: 'Write a Business Continuity Plan (BCP). Include: purpose, business impact analysis, RTO/RPO targets (RTO: 4 hours, RPO: 1 hour for critical systems), recovery team contact list, communication plan, alternate work procedures, annual test requirement. 600-900 words.' },
        'CC9.7': { name: 'Employee Offboarding Checklist', guidance: 'Write a detailed Employee Offboarding Security Checklist template. Format as a numbered checklist with: access revocation items (10+ specific systems: GitHub, AWS, Google Workspace, Slack, production databases, CI/CD, monitoring tools, VPN), equipment return, knowledge transfer, exit interview security briefing, final sign-off block.' },
      };
      const policyInfo = POLICY_PROMPTS[controlId];
      if (!policyInfo) return res.status(400).json({ error: 'No policy template available for ' + controlId });
      try {
        const prompt = `You are a SOC 2 compliance attorney and policy writer. Write the following policy document for a SaaS startup preparing for SOC 2 Type 1 audit.\n\nDocument: ${policyInfo.name}\nInstructions: ${policyInfo.guidance}\n\nFormat professionally:\n- Start with: [COMPANY NAME] - ${policyInfo.name}\n- Version: 1.0 | Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} | Owner: [OWNER ROLE]\n- Use clear section headers\n- End with: "Approved by: __________ [Title] Date: __________"\n\nOutput only the policy document text, no preamble.`;
        const text = await groqPost([{ role: 'user', content: prompt }], 1800, 0.2);
        const result = { controlId, policyName: policyInfo.name, text, generatedAt: new Date().toISOString() };
        await redis.set(cacheKey, JSON.stringify(result), { ex: 7 * 24 * 3600 });
        return res.status(200).json(result);
      } catch (err) { console.error('Policy gen error:', err.message); return res.status(500).json({ error: 'Could not generate policy. Please try again.' }); }
    }

    try {
      const { id } = req.query;

      if (id) {
        // Get single report by ID (timestamp key)
        const raw = await redis.get(`user:${userId}:report:${id}`);
        if (!raw) return res.status(404).json({ error: 'Report not found' });
        const report = typeof raw === 'object' ? raw : JSON.parse(raw);
        return res.status(200).json(report);
      }

      // List reports from a maintained per-user index (avoids O(N) KEYS scan).
      let ids = await redis.lrange(`user:${userId}:reports`, 0, 19);
      // Back-compat: if the index is empty, fall back to a one-time KEYS scan.
      if (!ids || !ids.length) {
        const keys = await redis.keys(`user:${userId}:report:*`);
        ids = (keys || []).map(k => k.split(':').pop());
      }
      if (!ids.length) return res.status(200).json({ reports: [] });

      const reports = [];
      for (const id of ids.slice(0, 20)) {
        try {
          const raw = await redis.get(`user:${userId}:report:${id}`);
          if (raw) {
            const r = typeof raw === 'object' ? raw : JSON.parse(raw);
            // Return summary only (no full content) for listing
            reports.push({
              id: r.id,
              generatedAt: r.generatedAt,
              score: r.score,
              overallRating: r.report?.overallRating,
              executiveSummary: r.report?.executiveSummary,
              aiGenerated: r.aiGenerated,
              generatedBy: r.generatedBy,
            });
          }
        } catch {}
      }
      reports.sort((a, b) => (b.generatedAt || 0) - (a.generatedAt || 0));
      return res.status(200).json({ reports });
    } catch (err) {
      console.error('Report list error:', err.message);
      return res.status(500).json({ error: 'Could not load reports.' });
    }
  }

  // ── POST: Generate audit readiness report via Groq ───────────
  if (req.method === 'POST') {
    if (!process.env.GROQ_API_KEY) {
      return res.status(500).json({ error: 'GROQ_API_KEY not configured.' });
    }

    // AI report generation is a paid feature — enforce server-side.
    const mode = await getUserMode(userId);
    if (!isPaidMode(mode)) {
      return res.status(402).json({ error: 'AI report generation requires a paid plan.' });
    }

    const rl = await checkRateLimit(userId, 'report', mode);
    if (!rl.ok) {
      return res.status(429).json({ error: `Report rate limit. Retry in ${rl.retryAfter}s.`, retryAfter: rl.retryAfter });
    }

    try {
      const { companyName, companySize, industry, currentTools } = req.body || {};
      const score = await getCurrentScore(userId);
      const controlsSummary = await buildControlsSummary(userId);

      // Build context string for company-specific personalization
      const companyContext = [
        companyName ? `Company: ${companyName}` : null,
        companySize ? `Company size: ${companySize}` : null,
        industry ? `Industry: ${industry}` : null,
        currentTools ? `Current tools/stack: ${currentTools}` : null,
      ].filter(Boolean).join('\n');

      const notStartedCount = controlsSummary.filter(c => c.status === 'NOT_STARTED').length;
      const inProgressCount = controlsSummary.filter(c => c.status === 'IN_PROGRESS').length;

      // ── Groq prompt ─────────────────────────────────────────────
      const prompt = `You are a SOC 2 compliance consultant (not a CPA auditor). You help companies prepare for SOC 2 Type 1 audits.

${companyContext}
Overall Readiness Score: ${score}%
Framework: SOC 2 Type 1
Controls NOT_STARTED: ${notStartedCount}
Controls IN_PROGRESS: ${inProgressCount}

Full Control Status:
${JSON.stringify(controlsSummary, null, 2)}

Your report should:
1. Be honest about gaps — do not minimize them
2. Provide SPECIFIC evidence each control needs (e.g., "CC6.2: Export a screenshot of your GitHub org settings showing 'Require two-factor authentication' is enabled")
3. Identify controls that are marked CONNECTED_AUTO or EVIDENCE_UPLOADED but may need additional evidence for an actual auditor
4. Include a realistic time estimate based on the NUMBER of NOT_STARTED controls (${notStartedCount} controls not started)
5. Focus only on controls that are NOT_STARTED or IN_PROGRESS for the criticalGaps and evidenceSuggestions

Do not suggest general best practices. Be specific to the controls that are NOT_STARTED or IN_PROGRESS.

Important: Include the exact disclaimer text in the 'disclaimer' field of the output:
"This report was generated by AuditReady AI to help you prepare for a SOC 2 audit. It is not a certified audit opinion and does not replace an attestation by a licensed CPA firm."

Output ONLY valid JSON matching this exact schema, no preamble, no markdown:
${JSON.stringify(REPORT_SCHEMA)}`;

      const responseText = await groqPost(
        [{ role: 'user', content: prompt }],
        1500,
        0.15 // Low temperature for deterministic, structured output
      );

      if (!responseText) return res.status(500).json({ error: 'Empty response from AI.' });

      const parsed = safeJsonParse(responseText);
      if (!parsed) {
        return res.status(200).json({ rawResponse: responseText, warning: 'Could not parse structured output — report generated but unstructured' });
      }

      // Store report in Redis
      const timestamp = Date.now();
      const reportId = timestamp.toString();
      const reportData = {
        id: reportId,
        userId,
        companyName: companyName || 'The Company',
        companySize: companySize || null,
        industry: industry || null,
        currentTools: currentTools || null,
        score,
        generatedAt: timestamp,
        controlsSummary,
        report: parsed,
        aiGenerated: true,
        generatedBy: 'Groq llama-3.3-70b-versatile',
      };

      await redis.set(`user:${userId}:report:${reportId}`, JSON.stringify(reportData));
      // Maintain a newest-first index so listing never needs a KEYS scan.
      await redis.lpush(`user:${userId}:reports`, reportId);
      await redis.ltrim(`user:${userId}:reports`, 0, 49);
      await trackUser(userId, 'report');

      return res.status(200).json({
        ok: true,
        reportId,
        report: parsed,
        score,
        generatedAt: timestamp,
        aiGenerated: true,
        generatedBy: 'Groq llama-3.3-70b-versatile',
      });

    } catch (err) {
      await logError('report_error', { msg: err.message, userId });
      return res.status(500).json({ error: 'Could not generate report. Please try again.' });
    }
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
